matrix:
  include:
  - language: python
    python: 3.6
    before_script:
      - python3 -m grpc_tools.protoc --proto_path=protos --python_out=api --grpc_python_out=api protos/nlp.proto
      - pip install pytest
    install:
      - pip install -r requirements.txt
    script:
      - python -m pytest api/server_test.py
    cache: pip
  - language: go
    node_js: 1.14
    before_install:
      - export GO111MODULE=on
      - source ~/virtualenv/python3.6/bin/activate
      - pip install -r requirements.txt
      - python3 -m grpc_tools.protoc --proto_path=protos --python_out=api --grpc_python_out=api protos/nlp.proto
    install:
      - go mod download
    script:
      - (python3 api/server.py &) && go test -v
notifications:
  email: false