matrix:
  include:
  - language: python
    python: 3.6
    before_script:
      - python3 -m spacy download en
      - pip install pytest
    install:
      - pip install -r requirements.txt
      - openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 365 -out server.crt -subj "/CN=localhost"
    script:
      - python -m pytest api/server_test.py
    cache: pip
  - language: go
    node_js: 1.14
    before_install:
      - export GO111MODULE=on
      - source ~/virtualenv/python3.6/bin/activate
      - pip install -r requirements.txt
      - python3 -m spacy download en
      - openssl req -newkey rsa:2048 -nodes -keyout server.key -x509 -days 365 -out server.crt -subj "/CN=localhost"
    install:
      - go mod download
    script:
      - (python3 api/server.py &) && go test -v -coverprofile=coverage.txt -covermode=atomic
notifications:
  email: false